from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import PayrollManagementViewSet, UserViewSet, payroll_calculation, user_annual_salary_revision, user_signup, user_login, get_unverified_users, get_verified_users
from .views import EmployerViewSet, employer_signup, employer_login, verify_users_by_id
from .views import PositionViewSet, leave_apply, get_approved_leave_manage, get_pending_leave_manage
from .views import get_rejected_leave_manage, update_leave_status, loss_of_pay
# user_detail, user_list,

router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'employers', EmployerViewSet)
router.register(r'positions', PositionViewSet)
router.register(r'Payroll',PayrollManagementViewSet)
# router.register(r'api', UserSignupViewSet)

urlpatterns = [
    # path('users-apis/', user_list),
    # path('users-apis/<int:pk>/', user_detail),
    path('api/user-signup/', user_signup),
    path('api/user-login/', user_login),
    path('api/employer-signup/', employer_signup),
    path('api/employer-login/', employer_login),
    path('employers/get-verified-users/', get_verified_users),
    path('employers/get-unverified-users/', get_unverified_users),
    path('employers/verify_user/<int:user_id>/', verify_users_by_id),
    path('users/leave-apply/', leave_apply),
    path('employers/get_approved_leave_manage/', get_approved_leave_manage),
    path('employers/get_pending_leave_manage/', get_pending_leave_manage),
    path('employers/get_rejected_leave_manage/', get_rejected_leave_manage),
    path('employers/update_leave_status/<int:user_id>/', update_leave_status),
    path('users/loss-of-pay/', loss_of_pay),
    path('employers/user_annual_salary_revision/<int:user_id>/',user_annual_salary_revision),
    path('employers/payroll_calculation',payroll_calculation),
    # {request.data.get('id')}
]


# Add the URLs generated by the router
urlpatterns += router.urls




































































